name: Build Wheel Action
description: Action for building FFmpeg and package wheel.
inputs:
  WHL_PLATFORM:
    description: "Wheel platform"
    required: false
    default: "manylinux2010_x86_64"
    type: string
  ARCH:
    description: "Architecture"
    required: false
    default: ""
    type: string
  CROSS_COMPILE:
    description: "Cross compile prefix"
    required: false
    default: ""
    type: string
  CROSS_COMPILE_PKG_SUFFIX:
    description: "Cross compiler package suffix"
    required: false
    default: ""
    type: string
  PLATFORM:
    description: "Platform"
    required: false
    default: ""
    type: string
  UPLOAD:
    description: "Whether to upload artifacts"
    required: false
    default: true
    type: boolean

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5.0.0
      with:
        python-version: "3.10"
        cache: pip

    - name: Setup environment variables
      shell: bash
      run: |
        echo "WHL_PLATFORM=${{ inputs.WHL_PLATFORM }}" >> $GITHUB_ENV
        echo "ARCH=${{ inputs.ARCH }}" >> $GITHUB_ENV
        echo "CROSS_COMPILE=${{ inputs.CROSS_COMPILE }}" >> $GITHUB_ENV
        echo "CROSS_COMPILE_PKG_SUFFIX=${{ inputs.CROSS_COMPILE_PKG_SUFFIX }}" >> $GITHUB_ENV
        echo "PLATFORM=${{ inputs.PLATFORM }}" >> $GITHUB_ENV

    - name: Install dependencies
      shell: bash
      run: |
        CROSS_COMPILE_PKG_SUFFIX=${{ env.CROSS_COMPILE_PKG_SUFFIX }} sh setup-dependencies.sh
        pip install build

    - name: List environment variables
      shell: bash
      run: |
        echo "WHL_PLATFORM=${{ env.WHL_PLATFORM }}"
        echo "ARCH=${{ env.ARCH }}"
        echo "CROSS_COMPILE=${{ env.CROSS_COMPILE }}"
        echo "CROSS_COMPILE_PKG_SUFFIX=${{ env.CROSS_COMPILE_PKG_SUFFIX }}"
        echo "PLATFORM=${{ env.PLATFORM }}"

    - name: Build FFmpeg
      shell: bash
      run: |
        ARCH=${{ env.ARCH }} CROSS_COMPILE=${{ env.CROSS_COMPILE }} PLATFORM=${{ env.PLATFORM }} PATH="`realpath llvm-mingw-*/bin/`:$PATH" sh build.sh
        find build/ffmpeg*/ -type f \( -name "ffmpeg" -o -name "ffmpeg.exe" -o -name "ffprobe" -o -name "ffprobe.exe" \) -exec cp {} src/xdcheckin_ffmpeg/bin/ \;

    - name: Build package
      shell: bash
      run: |
        python -m build -w -C="--build-option=--plat-name" -C="--build-option=${{ env.WHL_PLATFORM }}"
        echo "UPLOAD_NAME=dist-${{ env.WHL_PLATFORM }}" >> $GITHUB_ENV

    - name: Upload package
      uses: actions/upload-artifact@v4.3.1
      if: ${{ inputs.UPLOAD == 'true' }}
      with:
        if-no-files-found: error
        name: ${{ env.UPLOAD_NAME }}
        path: |
          dist/*.whl
