 name: Build for manylinux2010_i686

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Build FFmpeg and wheel
        uses: ./.github/actions/build-wheel
        with:
          WHL_PLATFORM: "manylinux2010_i686"
          ARCH: "i686"
          CROSS_COMPILE: "i686-linux-gnu"
          CROSS_COMPILE_PKG_SUFFIX: "i686-linux-gnu"
          PLATFORM: "linux"
