name: Build for macosx_12_0_x86_64

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-macosx_12_0_x86_64:
    name: Build
    runs-on: macos-12
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Build FFmpeg and wheel
        uses: ./.github/actions/build-wheel
        with:
          WHL_PLATFORM: "macosx_12_0_x86_64"
