name: Build for manylinux2014_aarch64

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Build FFmpeg and Package Wheel
        uses: ./.github/actions/build-wheel
        with:
          WHL_PLATFORM: "manylinux2014_aarch64"
          ARCH: "aarch64"
          CROSS_COMPILE: "aarch64-linux-gnu"
          PLATFORM: "linux"
