name: Build for manylinux2010_x86_64

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Build FFmpeg and Package Wheel
        uses: ./.github/actions/build-wheel
        with:
          WHL_PLATFORM: "manylinux2010_x86_64"
          ARCH: ""
          CROSS_COMPILE: ""
          PLATFORM: ""
