name: Build Packages

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-macosx_10_9_x86_64:
    name: Build for macosx_10_9_x86_64
    uses: ./.github/workflows/build-macosx_10_9_x86_64.yml

  build-macosx_11_0_arm64:
    name: Build for macosx_11_0_arm64
    uses: ./.github/workflows/build-macosx_11_0_arm64.yml

  build-manylinux2010_i686:
    name: Build for manylinux2010_i686
    uses: ./.github/workflows/build-manylinux2010_i686.yml

  build-manylinux2010_x86_64:
    name: Build for manylinux2010_x86_64
    uses: ./.github/workflows/build-manylinux2010_x86_64.yml

  build-manylinux2014_aarch64:
    name: Build for manylinux2014_aarch64
    uses: ./.github/workflows/build-manylinux2014_aarch64.yml

  build-manylinux2014_armv7l:
    name: Build for manylinux2014_armv7l
    uses: ./.github/workflows/build-manylinux2014_armv7l.yml

  build-musllinux_1_0_i686:
    name: Build for musllinux_1_0_i686
    uses: ./.github/workflows/build-musllinux_1_0_i686.yml

  build-musllinux_1_0_x86_64:
    name: Build for musllinux_1_0_x86_64
    uses: ./.github/workflows/build-musllinux_1_0_x86_64.yml

  build-musllinux_1_0_aarch64:
    name: Build for musllinux_1_0_aarch64
    uses: ./.github/workflows/build-musllinux_1_0_aarch64.yml

  build-musllinux_1_0_armv7l:
    name: Build for musllinux_1_0_armv7l
    uses: ./.github/workflows/build-musllinux_1_0_armv7l.yml

  build-win32:
    name: Build for win32
    uses: ./.github/workflows/build-win32.yml

  build-win_amd64:
    name: Build for win_amd64
    uses: ./.github/workflows/build-win_amd64.yml

  build-win_arm64:
    name: Build for win_arm64
    uses: ./.github/workflows/build-win_arm64.yml
