name: Test

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-manylinux2010_x86_64:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo sh setup-ubuntu.sh
